# aws codebuild configuration file
version: 0.1

environment_variables:
  plaintext:
    POWELL: "value"
            
phases:
  install:
    commands:
    
  build:
    commands:
      - echo $SHELL
      - env
      - ls -lR
      - set

artifacts:
