# aws codebuild configuration file
version: 0.1

environment_variables:
  plaintext:
    POWELL: "value"
            
phases:
  install:
    commands:
      - pip install -r ./cfm/requirements.txt
    
  build:
    commands:
      - echo $SHELL
      - env
      - ls -lR
      - set
      - python ./cfm/run.py -code > out.txt
      - unzip -d build build/python-v1.zip

artifacts:
  files:
    - build/*
    - out.txt
  discard-paths: yes
