# aws codebuild configuration file
version: 0.1

environment_variables:
  plaintext:
    POWELL: "value"
            
phases:
  build:
    commands:
      - echo $SHELL
      - env
      - ls -lR
      - ./cfm/run.py -h > out.txt
      - set

artifacts:
  files:
    - out.txt
  discard-paths: yes
