# aws codebuild configuration file
version: 0.1

environment_variables:
  plaintext:
    POWELL: "value"
            
phases:
  install:
    commands:
      - pip install -r ./cfm/requirements.txt
    
  build:
    commands:
      - echo $SHELL
      - env

      # create cloudformation templates, zip files, ... and deploy them
      - python ./cfm/run.py

      # create the build directory output from the python-v1 ingest program program
      # the build/ directory is the output of this stage in the pipeline (fed into the elasticbeanstalk deploy)
      - mv build/python-v1.zip .
      - rm -rf build
      - mkdir -p build
      - unzip -d build python-v1.zip

artifacts:
  files:
    - build/*
  discard-paths: yes
